// <auto-generated />
namespace ProjetoModeloDDD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class teste : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teste));
        
        string IMigrationMetadata.Id
        {
            get { return "201803160051025_teste"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
